### PR TITLE
Replace set-output by GITHUB_OUTPUT

### LINKED ISSUE #56: GitHub Actions: Deprecating save-state and set-output commands
Looking at the output of one of a recent docs validation run for amazon.aws I'm seeing:

```
 Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

It would appear that there's something that needs to change...

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #56.

### CODE REVIEW

**Comment by briantist** [comment]
looks great so far, but looking at the annotations, may have missed some: 
- https://github.com/ansible-community/github-docs-build/actions/runs/3254858651
- https://github.com/ansible-community/github-docs-build/actions/runs/3254858650

**Comment by felixfontein** [comment]
There's none more in this repository (I've grepped for it). Maybe some of these tests use actions from the `main` branch?

**Comment by briantist** [comment]
> There's none more in this repository (I've grepped for it). Maybe some of these tests use actions from the `main` branch?

Ok so it turns out these are from other actions we're using. We should update `setup-python` to use `v4`: the breaking change in that version is that it no longer has a default python version so if we're not already, we'll need to specify one (no big deal). Would you mind updating that in this PR?

The other thing causing the warnings is `download-artifact`, which unfortunately doesn't have a fix yet, so we'll just have to wait for it and update it later if it ends up being a new major version:
- https://github.com/actions/download-artifact/issues/185

**Review by briantist — APPROVED** [review]

**Comment by briantist** [comment]
thanks @felixfontein !

**Pull request merged**
